- name: Validating interface status
  block:
    - name: Validate interface link and protocol status
      ansible.builtin.assert:
        that:
          - parsed_interface.link_status == "up"
          - parsed_interface.link_status == "up"
        fail_msg: >-
          Interface {{ active_interface }} has link status {{ parsed_interface.link_status }}
          and protocol status {{ parsed_interface.link_status }}.
        success_msg: "Interface {{ active_interface }} is up/up"
        quiet: true
      register: interface_result

    - name: Update Successful Results
      ansible.builtin.set_fact:
        interface_results_pass: >-
          {{ interface_results_pass + [
            {
              "interface": active_interface,
              "state": "pass",
              "link_status": "up",
              "protocol_status": "up"
            }
          ] }}

  rescue:
    - name: Update Failure Results
      ansible.builtin.set_fact:
        interface_results_fail: >-
          {{ interface_results_fail + [
            {
              "interface": active_interface,
              "state": "fail",
              "reason": interface_result.msg
            }
          ] }}
