---
#
# Ansible Role to Validate Operational State
#
# Copyright (C) 2025 World Wide Technology
# All Rights Reserved
#
# Written by Nick Thompson (github/@nsthompson)
#

- name: Collect active interface information from NetBox for {{ inventory_hostname }}
  ansible.builtin.include_tasks: query_device_interfaces.yml

- name: Collect show interface output from {{ inventory_hostname }}
  ansible.builtin.include_tasks: query_show_interface.yml

- name: Define status_results dict for {{ inventory_hostname }}
  ansible.builtin.set_fact:
    status_results: {}

- name: Validate interface status on {{ inventory_hostname }}
  ansible.builtin.include_tasks: validate_interface_status.yml
  loop: "{{ active_interfaces }}"
  loop_control:
    loop_var: active_interface
