- name: Validating ospf routing
  block:
    - name: Validate OSPF Routes
      ansible.builtin.assert:
        that:
          - route.nexthop_ip in ospf_neighbor_addresses
          - route.protocol == "O"
        fail_msg: >-
          Route {{ route.network }} / {{ route.prefix_length }} is learned via the wrong next hop.
        quiet: true
      register: ospf_route_result

    - name: Update Successful Results
      ansible.builtin.set_fact:
        ospf_route_results_pass: >-
          {{ ospf_route_results_pass + [
              {
                "route": route.network,
                "prefix_length": route.prefix_length,
                "nexthop_ip": route.nexthop_ip,
                "nexthop_if": route.nexthop_if,
                "state": "pass"
              }
            ] }}
  rescue:
    - name: Update Failure Results
      ansible.builtin.set_fact:
        ospf_route_results_fail: >-
          {{ ospf_route_results_fail + [
              {
                "route": route.network,
                "prefix_length": route.prefix_length,
                "nexthop_ip": route.nexthop_ip,
                "nexthop_if": route.nexthop_if,
                "state": "fail",
                "reason": ospf_route_result.msg
              }
          ] }}
