- name: Validating ospf routing
  block:
    - name: Validate OSPF Neighbor Relationships
      ansible.builtin.assert:
        that:
          - neighbor.neighbor_id == hostvars[interface.value['neighbor']]['custom_fields']['ospfv2_router_id']
          - neighbor.state == "FULL/  -"
        fail_msg: >-
          Neighbor {{ neighbor.neighbor_id }} is misconfigured or not operational.
        success_msg: "Neighbor {{ neighbor.neighbor_id }} is operational."
        quiet: true
      register: ospf_neighbor_result

    - name: Update Successful Results
      ansible.builtin.set_fact:
        ospf_neighbor_results_pass: >-
          {{ ospf_neighbor_results_pass + [
              {
                "interface": interface.key,
                "neighbor": neighbor.neighbor_id,
                "address": neighbor.ip_address,
                "ospf_status": neighbor.state,
                "state": "pass"
              }
            ] }}
  rescue:
    - name: Update Failure Results
      ansible.builtin.set_fact:
        ospf_neighbor_results_fail: >-
          {{ ospf_neighbor_results_fail + [
              {
                "interface": interface.key,
                "state": "fail",
                "reason": ospf_neighbor_result.msg
              }
          ] }}
