- name: Validating BGP routing
  block:
    - name: Validate BGP Routes
      ansible.builtin.assert:
        that:
          - route.nexthop_ip in bgp_neighbor_addresses
          - route.protocol == "B"
        fail_msg: >-
          Route {{ route.network }} / {{ route.prefix_length }} is learned via the wrong next hop.
        quiet: true
      register: bgp_route_result

    - name: Update Successful Results
      ansible.builtin.set_fact:
        bgp_route_results_pass: >-
          {{ bgp_route_results_pass + [
            {
              "route": route.network,
              "prefix_length": route.prefix_length,
              "nexthop_ip": route.nexthop_ip,
              "state": "pass"
            }
          ] }}

  rescue:
    - name: Update Failure Results
      ansible.builtin.set_fact:
        bgp_route_results_fail: >-
          {{ bgp_route_results_fail + [
            {
              "route": route.network,
              "prefix_length": route.prefix_length,
              "nexthop_ip": route.nexthop_ip,
              "state": "fail",
              "reason": bgp_route_result.msg
            }
          ] }}
