- name: Query for active BGP sessions
  block:
    - name: Querying active BGP session for {{ inventory_hostname }}
      ansible.builtin.uri:
        url: "{{ netbox_url }}/api/plugins/bgp/session/?device={{ inventory_hostname }}&status=active"
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: true
        status_code: 200
      register: bgp_session_response

    - name: Parse BGP session data
      ansible.builtin.set_fact:
        bgp_session_data: >-
          {{ bgp_session_data | default([]) +
            [{
              "name": session.name,
              "description": session.description,
              "device": session.device.display,
              "site": session.site.name,
              "local_as": session.local_as.asn,
              "local_ip": session.local_address.address,
              "remote_as": session.remote_as.asn,
              "remote_ip": session.remote_address.address,
              "prefix_list_in": session.prefix_list_in,
              "prefix_list_out": session.prefix_list_out,
              "peer_group": session.peer_group,
              "tenant": session.tenant
            }]
          }}
      loop: "{{ bgp_session_response.json.results }}"
      loop_control:
        loop_var: session
  rescue:
    - name: Query failure - return empty list.
      ansible.builtin.set_fact:
        bgp_session_data: []
