---
#
# Ansible Role to Configure Base Device Settings
#
# Copyright (C) 2025 World Wide Technology
# All Rights Reserved
#
# Written by Nick Thompson (github/@nsthompson)
#

- name: Configure Cisco IOS Devices
  ansible.builtin.include_tasks: configure_cisco_ios.yml
  when: '"ios" in platforms'

- name: Configure Cisco IOS VTP Settings
  ansible.builtin.include_tasks: configure_cisco_vtp.yml
  when: '"ios" in platforms'
