---
config_contexts:
  - data:
      name: "Global AAA Configuration"
      weight: 100
      description: "Approved AAA Configuration for All IOS-XE Devices"
      active: true
      data:
        controller_tags:
          - device
        aaa_commands:
          - "aaa new-model"
          - "aaa authentication login default local"
          - "aaa authorization exec default local"
          - "aaa authorization network default local"
      platforms: ios
    state: present
  - data:
      name: "Globally Disabled Configuration"
      weight: 100
      description: "Default Disabled Configuration for All IOS-XE Devices"
      active: true
      data:
        controller_tags:
          - device
        disabled_commands:
          - "no ip http server"
          - "no ip http secure-server"
          - "no ip domain lookup"
      platforms: ios
    state: present
  - data:
      name: "Global Service Configuration Best Practices"
      weight: 100
      description: "Global Configuration Best Practices for All IOS-XE Devices"
      active: true
      data:
        controller_tags:
          - device
        service_configuration:
          password_encryption: true
          tcp_keepalives_in: true
          tcp_keepalives_out: true
          timestamps:
            - msg: debug
              enable: true
              timestamp: datetime
              datetime_options:
                localtime: true
                msec: true
                show_timezone: true
            - msg: log
              enable: true
              timestamp: datetime
              datetime_options:
                localtime: true
                msec: true
                show_timezone: true
      platforms: ios
    state: present
  - data:
      name: "Global VTP Configuration Best Practices"
      weight: 100
      description: "Global VTP Configuration Best Practices for All IOS-XE Devices"
      active: true
      data:
        controller_tags:
          - device
        vtp_commands:
          - "vtp mode transparent"
      platforms: ios
      roles:
        - core-switch
        - access-switch
    state: present
  - data:
      name: "Global OSPFv2 Configuration Best Practices"
      weight: 100
      description: "Global OSPFv2 Configuration Best Practices for IOS-XE Devices"
      active: true
      data:
        controller_tags:
          - routing
        ospf_configuration:
          log_adjacency_changes:
            detail: true
            set: true
      plaforms: ios
      roles:
        - core-switch
        - edge-router
    state: present
  - data:
      name: "Clock Configuration - US Central Time"
      weight: 100
      description: "US Central Time Configuration for IOS-XE Devices"
      active: true
      data:
        controller_tags:
          - device
        clock_commands:
          - "clock timezone CST -6 0"
          - "clock summer-time CDT recurring"
      platforms: ios
      regions:
        - US-MN
        - US-MO
    state: present
  - data:
      name: "Clock Configuration - US Eastern Time"
      weight: 100
      description: "US Eastern Time Configuration for IOS-XE Devices"
      active: true
      data:
        controller_tags:
          - device
        clock_commands:
          - "clock timezone EST -5 0"
          - "clock summer-time EDT recurring"
      platforms: ios
      regions:
        - US-Northeast
    state: present
  - data:
      name: "US NTP Configuration"
      weight: 100
      description: "US NTP Servers for IOS-XE Devices"
      active: true
      data:
        controller_tags:
          - device
        ntp_configuration:
          logging: true
          servers:
            - server: 128.101.101.101
              version: 2
              vrf: clab-mgmt
      platforms: ios
      regions: US
    state: present
  - data:
      name: "US-MN-MSP-01 Static Routes"
      weight: 100
      description: "Static Routes for Access Switches in US-MN-MSP-01"
      active: true
      data:
        controller_tags:
          - routing
        static_routes:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: "0.0.0.0/0"
                    next_hops:
                      - forward_router_address: 10.10.0.113
      platforms: ios
      sites: us-mn-msp-01
      roles: access-switch
    state: present
