---
controller_configuration_credentials_secure_logging: false
controller_credentials:
  - name: Github SSH Key
    description: Github SSH Key
    organization: Data-Driven-Automation
    credential_type: Source Control
    inputs:
      ssh_key_data: "{{ ssh_key_data }}"
      ssh_key_unlock: "{{ ssh_key_unlock }}"
  - name: NetBox API Key
    description: NetBox API Key
    organization: Data-Driven-Automation
    credential_type: NetBox API Key
    inputs:
      netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN', default=undef()) }}"
      netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API', default=undef()) }}"
      event_stream_url: "{{ lookup('ansible.builtin.env', 'EVENT_STREAM_URL', default=undef()) }}"
      event_stream_token: "{{ lookup('ansible.builtin.env', 'EVENT_STREAM_TOKEN', default=undef()) }}"
  - name: AAP Credential
    description: AAP Controller Credential
    organization: Data-Driven-Automation
    credential_type: Red Hat Ansible Automation Platform
    inputs:
      host: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST', default=undef()) }}"
      oauth_token: "{{ lookup('ansible.builtin.env', 'CONTROLLER_OAUTH_TOKEN', default=undef()) }}"
      verify_ssl: false
  - name: Containerlab
    description: Containerlab Host Credential
    organization: Data-Driven-Automation
    credential_type: Machine
    inputs:
      username: "{{ lookup('ansible.builtin.env', 'CONTAINERLAB_USER', default=undef()) }}"
      password: "{{ lookup('ansible.builtin.env', 'CONTAINERLAB_PASSWORD', default=undef()) }}"
      become_password: "{{ lookup('ansible.builtin.env', 'CONTAINERLAB_PASSWORD', default=undef()) }}"
      become_method: "sudo"
