---
eda_configuration_credentials_secure_logging: false
eda_credentials:
  - name: Github SSH
    description: Github SSH
    organization: Data-Driven-Automation
    credential_type: Source Control
    inputs:
      ssh_key_data: "{{ ssh_key_data }}"
      ssh_key_unlock: "{{ ssh_key_unlock }}"
  - name: NetBox Event-Stream Credential
    description: Basic Event-Stream Credential for NetBox
    organization: Data-Driven-Automation
    credential_type: Basic Event Stream
    inputs:
      username: NetBoxEDA
      password: "{{ netbox_eda_password }}"
  - name: AAP Credential
    description: AAP Credential
    organization: Data-Driven-Automation
    credential_type: Red Hat Ansible Automation Platform
    inputs:
      host: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST', default=undef()) + '/api/controller/' }}"
      oauth_token: "{{ lookup('ansible.builtin.env', 'CONTROLLER_TOKEN', default=undef()) }}"
      verify_ssl: false
