- name: Configure Netbox VLANs  # noqa: args[module]
  netbox.netbox.netbox_vlan:
    data:
      name: "{{ vlan.data.name }}"
      vid: "{{ vlan.data.id | default(omit) }}"
      description: "{{ vlan.data.description | default(omit) }}"
      site: "{{ vlan.data.site | default(omit) }}"
      status: "{{ vlan.data.status | default(omit) }}"
      vlan_group: "{{ vlan.data.vlan_group | default(omit) }}"
      vlan_role: "{{ vlan.data.vlan_role | default(omit) }}"
      tenant: "{{ vlan.data.tenant | default(omit) }}"
      comments: "{{ vlan.data.comments | default(omit) }}"
      custom_fields: "{{ vlan.data.custom_fields | default(omit) }}"
      tags: "{{ vlan.data.tags | default(omit) }}"
    state: "{{ vlan.state }}"
  loop: "{{ vlans }}"
  loop_control:
    loop_var: vlan
