- name: Configure Circuit {{ circuit.data.id }} from {{ circuit.data.provider }}
  netbox.netbox.netbox_circuit:
    data:
      provider: "{{ circuit.data.provider }}"
      cid: "{{ circuit.data.id }}"
      circuit_type: "{{ circuit.data.type }}"
      description: "{{ circuit.data.description | default(omit) }}"
      commit_rate: "{{ circuit.data.commit_rate | default(omit) }}"
      install_date: "{{ circuit.data.install_date | default(omit) }}"
      status: "{{ circuit.data.status | default(omit) }}"
      tenant: "{{ circuit.data.tenant | default(omit) }}"
      comments: "{{ circuit.data.comments | default(omit) }}"
      custom_fields: "{{ circuit.data.custom_fields | default(omit) }}"
      tags: "{{ circuit.data.tags | default(omit) }}"
    state: "{{ circuit.state }}"

- name: Configure A-side Circuit Terminations for Circuit {{ circuit.data.id }} from {{ circuit.data.provider }}
  netbox.netbox.netbox_circuit_termination:
    data:
      circuit: "{{ circuit.data.id }}"
      description: "{{ circuit.terminations.a.description | default(omit) }}"
      mark_connected: "{{ circuit.terminations.a.mark_connected | default(omit) }}"
      port_speed: "{{ circuit.terminations.a.port_speed | default(omit) }}"
      pp_info: "{{ circuit.terminations.a.pp_info | default(omit) }}"
      provider_network: "{{ circuit.terminations.a.provider | default(omit) }}"
      site: "{{ circuit.terminations.a.site | default(omit) }}"
      term_side: A
      upstream_speed: "{{ circuit.terminations.a.upstream_speed | default(omit) }}"
      xconnect_id: "{{ circuit.terminations.a.xconnect_id | default(omit) }}"
    state: "{{ circuit.terminations.a.state }}"
  when: circuit.terminations.a is defined

- name: Configure Z-side Circuit Terminations for Circuit {{ circuit.data.id }} from {{ circuit.data.provider }}
  netbox.netbox.netbox_circuit_termination:
    data:
      circuit: "{{ circuit.data.id }}"
      description: "{{ circuit.terminations.z.description | default(omit) }}"
      mark_connected: "{{ circuit.terminations.z.mark_connected | default(omit) }}"
      port_speed: "{{ circuit.terminations.z.port_speed | default(omit) }}"
      pp_info: "{{ circuit.terminations.z.pp_info | default(omit) }}"
      provider_network: "{{ circuit.terminations.z.provider | default(omit) }}"
      site: "{{ circuit.terminations.z.site | default(omit) }}"
      term_side: Z
      upstream_speed: "{{ circuit.terminations.z.upstream_speed | default(omit) }}"
      xconnect_id: "{{ circuit.terminations.z.xconnect_id | default(omit) }}"
    state: "{{ circuit.terminations.z.state }}"
  when: circuit.terminations.z is defined
