---
#
# Ansible Role to Configure Netbox Circuits
#
# Copyright (C) 2025 World Wide Technology
# All Rights Reserved
#
# Written by Nick Thompson (github/@nsthompson)
#

- name: Configure Netbox Circuit Types
  ansible.builtin.include_tasks: configure_circuit_types.yml
  when: circuit_types is defined

- name: Configure Netbox Circuit Providers
  ansible.builtin.include_tasks: configure_providers.yml
  when: providers is defined

- name: Configure Netbox Circuits
  ansible.builtin.include_tasks: configure_circuits.yml
  when: circuits is defined
  loop: "{{ circuits }}"
  loop_control:
    loop_var: circuit
