---
- name: Rulebook to debug received messages
  hosts: all
  gather_facts: false

  sources:
    - name: Listen for events from NetBox
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Debug all messages
      condition: true
      debug:
