---
- name: Rulebook to trigger automation to enforce state against a changed device
  hosts: all
  gather_facts: false

  sources:
    - name: Listen for events from NetBox
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Configure target device
      condition: event.payload.event == "updated"
      action:
        run_job_template:
          name: Configure Demo Network from NetBox
          organization: Data-Driven-Demo
          job_args:
            limit: "{{ event.payload.device }}"
