---
- name: Rulebook to trigger automation to enforce state against a changed device
  hosts: all
  gather_facts: false

  sources:
    - name: Listen for events from NetBox
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Configure target device
      condition: >-
          (event.payload.event == "updated" and event.payload.model == "device") or
          (event.payload.event == "updated" and event.payload.model == "interface")
      action:
        run_job_template:
          name: Configure Demo Network from NetBox
          organization: Data-Driven-Automation
          job_args:
            limit: "{{ event.payload.data.device.name }}"
            job_tags: "{{ event.payload.model }}"
    - name: Trigger webhook parsing playbook
      condition: event.payload.event == "updated" and event.payload.model == "configcontext"
      action:
        run_job_template:
          name: Parse NetBox Config Context Webhook
          organization: Data-Driven-Automation
          job_args:
            job_tags: "{{ event.payload.data.tags | join(',') }}"
