---
- name: Playbook to configure Netbox Cloud Lab Instance
  connection: local
  hosts: localhost
  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API', default=undef()) }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN', default=undef()) }}"

  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ netbox_token }}"

  pre_tasks:
    - name: Include vars from netbox_configs directory
      ansible.builtin.include_vars:
        dir: netbox_configs
        extensions: ["yml"]

    - name: Check for Netbox URL
      ansible.builtin.fail:
        msg: "netbox_url is undefined"
      when: not netbox_url is defined

    - name: Check for Netbox Token
      ansible.builtin.fail:
        msg: "netbox_token is undefined"
      when: not netbox_token is defined

  roles:
    - {role: configure_netbox_sites}
    - {role: configure_netbox_device_types}
    - {role: configure_netbox_customization}
    - {role: configure_netbox_racks}
    - {role: configure_netbox_ipam}
    - {role: configure_netbox_devices}
    - {role: configure_netbox_circuits}
    - {role: configure_netbox_cables}
    - {role: configure_netbox_data_sources}
    - {role: configure_netbox_config_contexts}
    - {role: configure_netbox_webhooks}
    - {role: configure_netbox_bgp}
