---
- name: Creating cable from {{ cable.data.termination_a.device ~ ' ' ~ cable.data.termination_a.name ~ '
    to ' ~ cable.data.termination_b.device ~ ' ' ~ cable.data.termination_b.name }} # noqa: args[module]
  netbox.netbox.netbox_cable:
    data:
      termination_a_type: "{{ cable.data.termination_a_type }}"
      termination_a: "{{ cable.data.termination_a }}"
      termination_b_type: "{{ cable.data.termination_b_type }}"
      termination_b: "{{ cable.data.termination_b }}"
      type: "{{ cable.data.type | default(omit) }}"
      color: "{{ cable.data.color | default(omit) }}"
      status: "{{ cable.data.status | default(omit) }}"
      description: "{{ cable.data.description | default(omit) }}"
      comments: "{{ cable.data.comments | default(omit) }}"
      label: "{{ cable.data.label | default(omit) }}"
      length: "{{ cable.data.length | default(omit) }}"
      length_unit: "{{ cable.data.length_unit | default(omit) }}"
      tenant: "{{ cable.data.tenant | default(omit) }}"
      custom_fields: "{{ cable.data.custom_fields | default(omit) }}"
      tags: "{{ cable.data.tags | default(omit) }}"
    state: "{{ cable.state }}"
  # idempotency bug with cable module - ignore errors for now
  failed_when: false
