---
- name: Playbook to generate a Containerlab Topology for the given sites and device-roles
  connection: local
  hosts: localhost
  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API', default=undef()) }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN', default=undef()) }}"

  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ netbox_token }}"

  pre_tasks:
    - name: Include vars from vars directory
      ansible.builtin.include_vars:
        dir: vars
        extensions: ["yml"]
        ignore_unknown_extensions: true

    - name: Check for Netbox URL
      ansible.builtin.fail:
        msg: "netbox_url is undefined"
      when: not netbox_url is defined

    - name: Check for Netbox Token
      ansible.builtin.fail:
        msg: "netbox_token is undefined"
      when: not netbox_token is defined

  roles:
    - { role: query_netbox_sites, when: sites is defined }
    - { role: generate_clab_topology, when: devices_by_site is defined }

  post_tasks:
    - name: Provide variables for deployment job in workflow
      ansible.builtin.set_stats:
        data:
          topology_file: "{{ topology_name }}.clab.yml"
          lab_name: "{{ topology_name }}"
      when: tower_job_id is defined
