---
# Create devices, without oob_ip address set
- name: Creating device {{ device.data.name }}  # noqa: args[module]
  netbox.netbox.netbox_device:
    data:
      name: "{{ device.data.name }}"
      description: "{{ device.data.description | default(omit) }}"
      device_role: "{{ device.data.device_role | default(omit) }}"
      device_type: "{{ device.data.device_type | default(omit) }}"
      site: "{{ device.data.site | default(omit) }}"
      location: "{{ device.data.location | default(omit) }}"
      rack: "{{ device.data.rack | default(omit) }}"
      face: "{{ device.data.face | default(omit) }}"
      position: "{{ device.data.position | default(omit) }}"
      status: "{{ device.data.status | default(omit) }}"
      airflow: "{{ device.data.airflow | default(omit) }}"
      asset_tag: "{{ device.data.asset_tag | default(omit) }}"
      cluster: "{{ device.data.cluster | default(omit) }}"
      comments: "{{ device.data.comments | default(omit) }}"
      config_template: "{{ device.data.config_template | default(omit) }}"
      custom_fields: "{{ device.data.custom_fields | default(omit) }}"
      local_context_data: "{{ device.data.local_context_data | default(omit) }}"
      platform: "{{ device.data.platform | default(omit) }}"
      primary_ipv4: "{{ device.data.primary_ipv4 | default(omit) }}"
      primary_ipv6: "{{ device.data.primary_ipv6 | default(omit) }}"
      serial: "{{ device.data.serial | default(omit) }}"
      tags: "{{ device.data.tags | default(omit) }}"
      tenant: "{{ device.data.tenant | default(omit) }}"
      vc_position: "{{ device.data.vc_position | default(omit) }}"
      vc_priority: "{{ device.data.vc_priority | default(omit) }}"
      virtual_chassis: "{{ device.data.virtual_chassis | default(omit) }}"
    state: "{{ device.state }}"

- name: Configuring interfaces on {{ device.data.name }}  # noqa: args[module]
  netbox.netbox.netbox_device_interface:
    data:
      name: "{{ interface.name }}"
      device: "{{ interface.device }}"
      description: "{{ interface.description | default(omit) }}"
      bridge: "{{ interface.bridge | default(omit) }}"
      duplex: "{{ interface.duplex | default(omit) }}"
      enabled: "{{ interface.enabled | default(omit) }}"
      form_factor: "{{ interface.form_factor | default(omit) }}"
      label: "{{ interface.label | default(omit) }}"
      lag: "{{ interface.lag | default(omit) }}"
      mac_address: "{{ interface.mac_address | default(omit) }}"
      mark_connected: "{{ interface.mark_connected | default(omit) }}"
      mgmt_only: "{{ interface.mgmt_only | default(omit) }}"
      mode: "{{ interface.mode | default(omit) }}"
      mtu: "{{ interface.mtu | default(omit) }}"
      parent_interface: "{{ interface.parent_interface | default(omit) }}"
      poe_mode: "{{ interface.poe_mode | default(omit) }}"
      poe_type: "{{ interface.poe_type | default(omit) }}"
      speed: "{{ interface.speed | default(omit) }}"
      tagged_vlans: "{{ interface.tagged_vlans | default(omit) }}"
      tx_power: "{{ interface.tx_power | default(omit) }}"
      type: "{{ interface.type | default(omit) }}"
      untagged_vlan: "{{ interface.untagged_vlan | default(omit) }}"
      vrf: "{{ interface.vrf | default(omit) }}"
      wwn: "{{ interface.wwn | default(omit) }}"
      custom_fields: "{{ interface.custom_fields | default(omit) }}"
      tags: "{{ interface.tags | default(omit) }}"
    state: "{{ device.state }}"
  when: device.interfaces is defined
  loop: "{{ device.interfaces }}"
  loop_control:
    loop_var: interface

- name: Configuring IP Addresses  # noqa: args[module]
  netbox.netbox.netbox_ip_address:
    data:
      address: "{{ ip.address }}"
      prefix: "{{ ip.prefix | default(omit) }}"
      vrf: "{{ ip.vrf | default(omit) }}"
      family: "{{ ip.family | default(omit) }}"
      description: "{{ ip.description | default(omit) }}"
      interface: "{{ ip.interface | default(omit) }}"
      dns_name: "{{ ip.dns_name | default(omit) }}"
      assigned_object: "{{ ip.assigned_object | default(omit) }}"
      role: "{{ ip.role | default(omit) }}"
      status: "{{ ip.status | default(omit) }}"
      comments: "{{ ip.comments | default(omit) }}"
      tenant: "{{ ip.tenant | default(omit) }}"
      nat_inside: "{{ ip.nat_inside | default(omit) }}"
      custom_fields: "{{ ip.custom_fields | default(omit) }}"
      tags: "{{ ip.tags | default(omit) }}"
    state: "{{ ip.state }}"
  when: device.ip_addresses is defined
  loop: "{{ device.ip_addresses }}"
  loop_control:
    loop_var: ip

# Update devices with oob_ip address
- name: Setting device {{ device.data.name ~ ' OOB IP to ' ~ device.data.oob_ip }}  # noqa: args[module]
  netbox.netbox.netbox_device:
    data:
      name: "{{ device.data.name }}"
      oob_ip: "{{ device.data.oob_ip }}"
    state: "{{ device.state }}"
  when: device.data.oob_ip is defined
